sudo: required

services:
  - docker

language: go
go:
  - 1.7.x

env:
  global:
    - secure: "cK1X+8tbMEp1p1Es/6VfBBDeAUE/BsOHIzmkHvNzMhBvdI8lAFsbAyzYJpfnjGC1vQLsF3hJa5eN21ZttlX4MDLYQ4Z6HiGyNGuPW64Auo0GmQtIP5UNSUDoHjQpkjr5qNotGbrKViyiK9tgnJgokQh3ErS7lnp5kv+LsYhA0uA96lp6DPcngQb5HnAiaOGA87YXWiuayBQ0t9i0NoPfTPeRP9f+CYpTQzOpn0lbHBDohDZfTeE9J1hLEptEUJkJSTnTgVdw6+XScRjHJx7RY3sm7QOj5h6lgn9Vb1okkwo6gzrAnwcos+LcdjQGu+ylzepDiG7gRGhnnTaBfPEQuxB5aR8H7/r8rNknbKG2pfX0Hb7uMr0wajMq6ug+3PUmz0cICLFHLDuSBw93wRXglT/JbEO+/SLyHXA58/CGrDQ1ypv6W72znQEO5WVa6ViYvQ+2uwctnXDuksNs8xKlPUG0iHv1eti0gMRXYtZ0siIr9oPQwhIwPlVIRL6u3xtY+mMmrJ0CMRyfwDUAZnWZb8h76EsKaJZLTsuz/WMZZJKiCG179iDeI6kZNZQrrnEjVY/UgE8Dm9MlVCf/SU9LNF1eEunR8ZaI9TcnhJZeKkQk5mWdNhgcTpNppHf6DzCTkDoKqdepM+yVxnWs2fKPGOc60mSypbVwKXbQeEkCYfQ=" # DOCKER_EMAIL
    - secure: "hf5bMeS5bMk+AYzDnimBP+EGJjoSnRJL01YbXAPa3UYkpODFSUlj+VSGsdT1N8fKJ7UINx2RdodoIQpZZj7fAhfoZKqWjavEmSSFQBYLnZJyJvCF84l0NYNsxvBXUWtPyKF3hUSZdRfhZjRaiB1ZRUvdzB/pU623vxU969IeaqP1r3jYfSk7w33K1M+lelJ6arbXVpyW4wa3cQ6GOzcTq248VFCB1Za/fCfN1mAwQAB5T9xnEnNbrlHP/OkLqUchxh4qVMkatjU0vxD3XYzg4GVaUxR5oF5nxWiv2HnIWxsEd7DcegtzEw9QFAhR0OjpHqU/OFhKmcmr8xh2ByWwsdev6llsHivd+P3FnvyPvwn7mfOJgsYyQQLuM5/lrSzT20wp8SG73rNroe/hcQBdhGgulKwMRPaTRk8Q1gptTpiDERE22vM2LhTNXEnzompQNfERPP8jXnBJ5FwVvptLg5NPDQ4f29wxkEHLxZVi4b612B3rwgMzGh5ywd+WGchcDBDDbrPd3hm2gnMWINGClspFChChBpCZ8agedRldC7TSbhLXkDPHzvzbqd35ugkBjDFjCJwhd0A8GqsjLOPQk8v9f4Uqyn3L8Sv43/zjAJEGCLKGjd4YouqqrkL21tyKsg5XJLI2GXaLzQkXhBtqeUaqiTfiZQyokNqcpgwN1vo=" # DOCKER_USER
    - secure: "NmMPe/qQTO0HLBgHkDHMS7+Hu8jAx9x6H/BSpvpwEoxWbM9U1I/rHo2xrW55y3tu6xIa6RWHa5IAh1B9D/sCdhM/bES2nlLYf3zmgE+zmFspfenQdOfkkvp84ymw9x1sVGIk/xPOHSCJbhQhdr367JcMTOn9LEUliccobwVAFbf5V02MbNZm2KBvALx/Q+0HdqLpipV45SG5xvlUxjj2j0aAjEhN/yBnunDxfiv/q85HWh8kibK+ktSmUfsp+dI5bHZ/u/pRrF8Y2bUf7WB8zUSoA/BE9Y+8qcpWOgGXdtnw64ijTRhiTTqD5P54dLL90VOXTIYYNKb0Lt0cxTufdU9dNFGXYCJmQtGzoJ8z000QZzathkTq4aFTbUf23nqlr2Q143MBcgA+7YOmLOJ1XShikCWvyVUCW18tEkKnnR2txXiLkEVMtXAj5fYRzj+HJNNgUValCoGLUqQjVOwJ46TJQe/whpCLFnVEvIVmU6VhBDR+x9ikSOHAer6UDV6OMqWQhRR/4cklK7lcuEHjRUDGP01SHJuJSLicdCG8LEV3Sv4Aww8eTKl3Td+M6AvOie6i8fqf6c8ZudW1iBO5/5WM95urGUmuQiEEor3l99/3AMAlW8DERY35+MIWbosx+w6YNcQgwWtTexMirI/dn8T9ASvzr6v0MtefM+zip00=" # DOCKER_PASS
    - REGION=hk
    - ENVIRONMENT=dev
    - COMMIT=${TRAVIS_COMMIT::7}
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS

  #TAG
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "$ENVIRONMENT-$REGION-latest"; else echo $TRAVIS_BRANCH ; fi`

  # USERS
  - export CONFIG=zanhsieh/cinema-users
  - docker build -t $CONFIG:$ENVIRONMENT-$REGION-$COMMIT ./users
  - docker tag $CONFIG:$ENVIRONMENT-$REGION-$COMMIT $CONFIG:$TAG
  - docker push $CONFIG

  # SHOWTIMES
  - export CONFIG=zanhsieh/cinema-showtimes
  - docker build -t $CONFIG:$ENVIRONMENT-$REGION-$COMMIT ./showtimes
  - docker tag $CONFIG:$ENVIRONMENT-$REGION-$COMMIT $CONFIG:$TAG
  - docker push $CONFIG

  # MOVIES
  - export CONFIG=zanhsieh/cinema-movies
  - docker build -t $CONFIG:$ENVIRONMENT-$REGION-$COMMIT ./movies
  - docker tag $CONFIG:$ENVIRONMENT-$REGION-$COMMIT $CONFIG:$TAG
  - docker push $CONFIG

  # BOOKINGS
  - export CONFIG=zanhsieh/cinema-bookings
  - docker build -t $CONFIG:$ENVIRONMENT-$REGION-$COMMIT ./bookings
  - docker tag $CONFIG:$ENVIRONMENT-$REGION-$COMMIT $CONFIG:$TAG
  - docker push $CONFIG