apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
  name: bookings
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: bookings
    spec:
      containers:
      - env:
        - name: VIRTUAL_HOST
          value: bookings.local
        image: cinema/bookings
        name: cinema-bookings
        resources: {}
      restartPolicy: Always
