apiVersion: v1
kind: Service
metadata:
  labels:
    service: db
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
  name: db
spec:
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  selector:
    app: {{ template "fullname" . }}
    service: db
status:
  loadBalancer: {}
