apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: movies
    release: "{{ .Release.Name }}"
  name: movies
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        component: movies
    spec:
      containers:
      - env:
        - name: VIRTUAL_HOST
          value: movies
        image: zanhsieh/cinema-movies:{{ .Values.environment }}-{{ .Values.region }}-latest
        name: cinema-movies
        ports:
          - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /movies
            port: 8080
          periodSeconds: 1
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 10
        resources: {}
      restartPolicy: Always
