apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
  name: movies
spec:
  rules:
  - host: movies.zanhsieh.net
    http:
      paths:
      - path: /movies
        backend:
          serviceName: movies
          servicePort: 80
