apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: movies
    release: "{{ .Release.Name }}"
  name: movies
spec:
  ports:
  - name: http
    port: 81
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ template "fullname" . }}
    component: movies
  type: NodePort
