apiVersion: v1
kind: Service
metadata:
  labels:
    service: movies
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
  name: movies
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    app: {{ template "fullname" . }}
    service: movies
status:
  loadBalancer: {}
