apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
  name: proxy
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ template "fullname" . }}
        service: proxy
    spec:
      containers:
      - image: jwilder/nginx-proxy
        name: cinema-nginx-proxy
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /tmp/docker.sock
          name: proxy-claim0
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: proxy-claim0
        persistentVolumeClaim:
          claimName: proxy-claim0
          readOnly: true
