apiVersion: v1
kind: Service
metadata:
  labels:
    service: proxy
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
  name: proxy
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    app: {{ template "fullname" . }}
    service: proxy
status:
  loadBalancer: {}
