apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
  name: showtimes
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        service: showtimes
    spec:
      containers:
      - env:
        - name: VIRTUAL_HOST
          value: showtimes.local
        image: zanhsieh/cinema-showtimes
        name: cinema-showtimes
        resources: {}
      restartPolicy: Always
