apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
  name: users
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        service: users
    spec:
      containers:
      - env:
        - name: VIRTUAL_HOST
          value: users.zanhsieh.net
        image: zanhsieh/cinema-users:{{ .Values.environment }}-{{ .Values.region }}-latest
        name: cinema-users
        ports:
          - containerPort: 8080
        resources: {}
      restartPolicy: Always
