apiVersion: v1
kind: Service
metadata:
  labels:
    service: users
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
  name: users
spec:
  clusterIP: None
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: {{ template "fullname" . }}
    service: users