apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: users
    release: "{{ .Release.Name }}"
  name: users
spec:
  ports:
  - name: http
    port: 83
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ template "fullname" . }}
    component: users
  type: NodePort